version: '3'
services:
 kaillera:
  hostname: ${hostname}
  image: lscr.io/linuxserver/medusa:latest
  logging:
    driver: "json-file"
    options:
      max-file: "3"
      max-size: "10m"
  container_name: ${hostname}
  restart: always
  ports:
   - 8081:8081
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Etc/UTC
  network_mode: bridge
  extra_hosts:
   - host.docker.internal:172.17.0.1
   - gateway.docker.internal:172.17.0.1
  volumes: 
   - ./medusa/config:/config
   - ./downloads:/downloads
   - ./tv/shows:/tv
#  mem_limit: 1000m


#${} 
